include: /.gitlab/template.yml

._default_build_script:
  variables:
    RENAMED_BUILD_DIR: build_${IDF_VER}_${TARGET}
  script:
    - export IDF_TARGET=${TARGET}
    - idf.py build
    - mv build ${RENAMED_BUILD_DIR}

._default_build_artifacts:
  artifacts:
    name: "artifacts-${TEST_DIRNAME}-${TARGET}-${IDF_VER}-${CI_COMMIT_REF_SLUG}"
    paths:
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/flasher_args.json"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/*.bin"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/*.map"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/*.elf"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/bootloader/bootloader.bin"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/bootloader/bootloader.elf"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/bootloader/bootloader.map"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/partition_table/*.bin"
      - "test_apps/${TEST_DIRNAME}/${RENAMED_BUILD_DIR}/config/sdkconfig.json"
    expire_in: 1 week

build (basic):
  extends:
    - ._default_build_script
    - ._default_build_artifacts
    - .default_matrix
    - .build_template
  variables:
    TEST_DIRNAME: esp_amp_basic_tests

build (light sleep):
  extends:
    - ._default_build_script
    - ._default_build_artifacts
    - .subcore_type_lp_matrix
    - .build_template
  variables:
    TEST_DIRNAME: esp_amp_light_sleep_tests
